### PR TITLE
Adding in High Eccentricity Corrections and Sundberg-Cooper

### PR DESCRIPTION
**Pull request by jrenaud90**
Hey @MarcNeveu - Finally had a chance to push these changes over. Unfortunately, I still am unable to get IcyDwarf working on my machines, so I can not test these changes. On paper they should work, but you will want to test them before accepting anything. 

I also am opening this pull request more of a chance for us to discuss these upgrades, more iterations are likely required. Specifically, the high eccentricity model I added in only applies to the tidal heating, not the orbital evolution. ID uses a different orbital evolution model than our PSJ paper, so implementing the higher corrections is not quite a copy and paste like it was for tidal heating. I can take a look at that later but wanted to get something over to you asap.

There are now 3 eccentricity models that only affect tidal heating.
`eccentricitymodel = 0` is the regular e^2 (same as you had before)
`eccentricitymodel = 1` calculates up to e^10 using a CPL-like approach (explained below)
`eccentricitymodel = 2` calculates up to e^10 using a CTL-like approach (explained below)

Both of these new additions are technically not correct since I have not implemented a tidal mode model. But they should be good estimates.
CPL-like: 
- Any multiplier to the forcing frequency is ignored. 
    - `-Im[k(w)] = -Im[k(2 * w)] = -Im[k(3 * w)] = -Im[k(4 * w)] = ...`
- This is somewhat analogous to Goldreich and Soter (1966) type method.

CTL-like:
- Any multiplier to the forcing frequency is brought outside the rheology function. 
    - `-Im[k(2 * w)] = -2 * Im[k2(w)]; -Im[k(3 * w)] = -3 * Im[k(w)]; -Im[k(4 * w)] = -4 * Im[k(w)]; ...`
- This is exactly the Wisdom 2008 approach.
- This probably preferable, but (at least initially) you should try making some results using all 3 models and compare.

Like our paper stated, these corrections for heating start to change the results around e=0.1 and lead to major changes around e=0.4. Since I did not go all the way to e^20, I would begin to not trust the results for e>~0.7 (See Fig.2 of PSJ paper).

The addition of Sundberg-Cooper was straight forward. I calculate the complex shear in a slightly different approach then your other models: I find the complex compliance and then just invert it. If that works for you and doesn't cause issues then I can change the other models to match the nomenclature. Or vice versa if you would rather I write the complex rigidity directly (warning: it is big and ugly).

Cheers,
Joe

PS: I also think I ran into some inconsistencies w/ spaces vs. tabs. I know C doesn't care, but just a heads up if my changes end up looking odd in your text editor/IDE.

### CODE REVIEW

**Comment by jrenaud90** [comment]
Hmm, Re: Orbital changes; looking at line: https://github.com/MarcNeveu/IcyDwarf/blob/dcb4bb279fa66b77fcb2f31edcffb1821f14801f/IcyDwarf/Orbit.h#L462

It looks like you use the tidal heating to calculate the change in eccentricity? So perhaps the eccentricity corrections _will_ carry over to the orbital changes.

**Comment by MarcNeveu** [comment]
Thanks so much Joe. Your changes look good. You seem understand exactly how I've coded IcyDwarf! And thanks for going as far as updating the input files.

It's up to you if you'd like to change the nomenclature for the other rheological models. I am fine leaving them as is, but if the compliance format is more compact for the others too we can change it. Let's definitely keep the compliance approach for the Sundberg-Cooper rheology.

GitHub (and probably my editor too, I use Eclipse) seems agnostic to spaces vs. tabs, which is probably why there are inconsistencies.

Yes, I use the tidal heating to calculate the change in orbital parameters, so the eccentricity corrections should carry over to the orbital changes. But I don't know if this is done with the same level of fidelity as with equations that express da/dt and de/dt directly as a function of e to order 10. I don't think so.

What's holding you back from being able to install IcyDwarf? The R and PHREEQC dependencies? I'd be happy to help.

**Comment by jrenaud90** [comment]
Hey Marc - Just added another commit as I noticed a few bugs. Sounds good re: rheology funcs and orbital changes. The orbital evolution should be fine until we add NSR and then it will be incorrect (the tidal heating is one part of the evolution, there is an angular momentum exchange that will be lost). 

Long-term we will want to use the prop matrix method to calculate the surface love number and then send it to a function to find the tidal potential derivatives which can then be sent to the orbital/rotational evolution. This won't be hard, the hardest part is figuring out how to handle the modes.

So regarding installing ID - it has been a while since I attempted it, I will try again this week and see what my specific issue was, but I believe it had to do with dependencies. 

As an aside, I am also working on making some changes to allow it to work on Windows. These are non-trivial changes though so it will take some time to figure that out.

**Comment by jrenaud90** [comment]
Oh, one question that may affect this PR: I noticed a flag for retrograde orbits. How does IcyDwarf handle this? Is `omega_tide` allowed to be negative? The way TidalPy handles this is that the sign here changes the sign of -Im[k2] but the actual calculation of the rheology only takes in the abs(w) of each mode (Michael's papers use `\chi` to describe this). The sign change of -Im[k2] has no affect on tidal heating since it carries a frequency multiplier on the outside: `w * -Im[k2]`, but the potential derivatives do not so the sign does matter to them.

I am about to push another commit that affects each of the rheologies when the freq is ~ 0. This is obviously not an issue for orbital motion, but if we use the same rheology funcs for the tidal mode case then some of the mode's are often = 0.

**Comment by MarcNeveu** [comment]
Thanks!

The retrograde flag affects only the sign of the semi-major axis evolution (secular and resonant) in `Orbit.h`, so `omega_tide` is treated as always positive. We can change that.

FYI, I think you introduced a typo at l. 37 of `Thermal.h`: `Crack_size`    ;-)

**Comment by jrenaud90** [comment]
Woah... Good catch. No idea how I did that.

**Pull request merged**
